# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user',
            new_name='submit',
        ),
    ]
