# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_auto_20170328_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='submit',
            new_name='user_submit',
        ),
    ]
