# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='item',
            new_name='item_name',
        ),
    ]
