# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0003_book_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='author_app.Author'),
        ),
    ]
